swagger: "2.0"
info:
  description: "Wallet API para realização de transferências de forma simples."
  version: "1.0.0"
  title: "Wallet API"
  termsOfService: ""
  contact:
    email: "echoclaudio@icloud.com"
host: "127.0.0.1:8000"
basePath: "/api"

# Groups
tags:
- name: "authentication"
  description: "Rotas para cadastro e login na API"
  
- name: "transaction"
  description: "Rota para iniciar transação de valores"
  
schemes:
- "http"

# Routes
paths:

  # Public routes 
  /register:
    post:
      tags:
      - "authentication"
      summary: "Criar um usuário para logar na aplicação"
      description: "Cria um usuário na API para logar e poder efetuar a transação de valores"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cria um usuário"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Sucesso ao criar usuário"
        "500":
          description: "Erro ao criar usuário"
  
  /login:
    post:
      tags:
      - "authentication"
      summary: "Loga na aplicação"
      description: "Ao logar na aplicação irá ser retornado o token de autenticação do usuário para fazer a transação de valores na API"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "Email do usuário"
        required: true
        type: "string"
        format: "string"
      - name: "password"
        in: "formData"
        description: "Senha do usuário"
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "Recebe o access token via header (Authorization)"
        "401":
          description: "Credenciais inválidas"
        "500":
          description: "Falha ao logar na API"

  # Private routes
  /transaction:
    post:
      tags:
      - "transaction"
      summary: "Executa uma transação de valores"
      description: "Efetua a transação de valores de um usuário comum para usuário comum ou para loja. Usuários lojistas não podem efetuar a transação apenas recebem."
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cria uma transação"
        required: true
        schema:
          $ref: "#/definitions/Transactions"
      responses:
        "200":
          description: "Sucesso ao criar transação"
        "500":
          description: "Erro ao criar transação"
      security:
        - ApiKeyAuth: []
        
# Models
definitions:
  User:
    type: "object"
    properties:
        id:
          type: "integer"
          format: "int64"
        user_type_id:
          $ref: "#/definitions/UserTypes"
        name:
          type: "string"
          description: "Nome do usuário"
          maxLength: 100 
          example: "Claudio Emmanuel de Araujo Souza"
        cpf_cnpj:
          type: "string"
          description: "CPF ou CNPJ do usuário"
          maxLength: 18
          example: "094.312.736-08"
        email:
          type: "string"
          description: "Email do usuário"
          example: "echoclaudio@icloud.com"
        password:
          type: "string"
          description: "Senha do usuário"
    xml:
      name: "User"

  UserTypes:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "Nome do tipo de usuário"
        maxLength: 100 
        example: "Common"
    xml:
      name: "UserTypes"
      
  Transactions:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_id:
        $ref: "#/definitions/User"
      payee_id:
        $ref: "#/definitions/User"
      value:
        type: "number"
        description: "Valor da transação entre os usuários"
    xml:
      name: "Transactions"
      
securityDefinitions:
  ApiKeyAuth:        
    type: apiKey
    in: header    
    name: "Authorization"  